apiVersion: v1
kind: Service
metadata:
  name: yata-svc
  labels:
    app: yata-svc
spec:
  type: NodePort
  selector:
    app: yata-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
