#!/bin/bash

REMOTE_HOST=paris-playground
HOST_DOMAIN=ec2-35-180-55-68.eu-west-3.compute.amazonaws.com

SETUP_DEPENDENCIES="gcc gcc-c++ patch readline readline-devel zlib zlib-devel \
  libffi-devel openssl-devel make bzip2 autoconf automake libtool bison sqlite-devel nginx"

ssh $REMOTE_HOST "sudo yum install $SETUP_DEPENDENCIES"

SETUP_RUBY="curl -sSL https://rvm.io/mpapis.asc | gpg2 --import - && \
  curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import - && \
  curl -L get.rvm.io | bash -s stable && \
  source /home/ec2-user/.rvm/scripts/rvm && \
  rvm reload && \
  rvm install 2.7 && \
  rvm use 2.7 --default"

ssh $REMOTE_HOST "$SETUP_RUBY"

APP_FOLDER=yata-web

ssh $REMOTE_HOST "mkdir -p $APP_FOLDER/tmp/pids"
ssh $REMOTE_HOST "mkdir -p $APP_FOLDER/db"

scp -r app/ config/ bin/ lib/ iac-deploy/ Gemfile Gemfile.lock Rakefile LICENSE README.md $REMOTE_HOST:~/$APP_FOLDER

ssh $REMOTE_HOST "echo \"export APP_PROTOCOL=http\" >> ~/.bashrc"
ssh $REMOTE_HOST "echo \"export APP_HOST=$HOST_DOMAIN\" >> ~/.bashrc"
ssh $REMOTE_HOST "echo \"export APP_PORT=4242\" >> ~/.bashrc"

SETUP_SYSTEMD="sudo cp $APP_FOLDER/iac-deploy/systemd/yata.service /etc/systemd/system/yata.service && \
  sudo systemctl enable yata && \
  sudo systemctl start yata"

ssh $REMOTE_HOST "$SETUP_SYSTEMD"

SETUP_NGINX="sudo cp $APP_FOLDER/iac-deploy/nginx/yata.conf /etc/nginx/conf.d/yata.conf && \
  sudo nginx -t && \
  sudo service nginx restart"

ssh $REMOTE_HOST "$SETUP_NGINX"
