#!/bin/bash

REMOTE_HOST=paris-playground
HOST_DOMAIN=yata42.online

SETUP_DEPENDENCIES="gcc gcc-c++ patch readline readline-devel zlib zlib-devel \
  libffi-devel postgresql-devel openssl-devel make bzip2 autoconf automake libtool bison sqlite-devel \
  nginx certbot certbot-nginx docker"

ssh $REMOTE_HOST "sudo yum install -y $SETUP_DEPENDENCIES"
ssh $REMOTE_HOST "sudo service docker start"

APP_FOLDER=yata-web

ssh $REMOTE_HOST "mkdir -p $APP_FOLDER/tmp/pids"

scp -r app/ config/ bin/ lib/ database/ iac-deploy/ Gemfile Gemfile.lock Rakefile Makefile LICENSE README.md $REMOTE_HOST:~/$APP_FOLDER
ssh $REMOTE_HOST "bash -lc \"cd yata-web && cp database/config.production.yml database/config.yml\""

ssh $REMOTE_HOST "bash -lc \"cd yata-web && make startpg\""
ssh $REMOTE_HOST "bash -lc \"cd yata-web && make migratedb\""

SETUP_SYSTEMD="sudo cp $APP_FOLDER/iac-deploy/systemd/yata.service /etc/systemd/system/yata.service && \
  sudo systemctl enable yata && \
  sudo systemctl restart yata"

ssh $REMOTE_HOST "$SETUP_SYSTEMD"

SETUP_NGINX="sudo cp $APP_FOLDER/iac-deploy/nginx/yata.conf /etc/nginx/conf.d/yata.conf && \
  sudo nginx -t && \
  sudo service nginx restart"

ssh $REMOTE_HOST "$SETUP_NGINX"
