development:
  adapter: postgres
  dbname: yata
  host: yata-db
  port: 5432
  user: yatadev
  password: yatadev

test:
  adapter: filesystem
  dbname: yata_test

production:
  adapter: postgres
  dbname: yata
  host: yata-db-0.yata-db-svc
  port: 5432
  user: yataprod
  password: yataprod
