development:
  adapter: postgres
  dbname: yata
  host: yata-db
  port: 5432
  user: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  adapter: filesystem
  dbname: yata_test

production:
  adapter: postgres
  dbname: yata
  host: <%= ENV['POSTGRES_HOST'] %>
  port: 5432
  user: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
