apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: yata-db
  name: yata-db
spec:
  serviceName: yata-db-svc
  replicas: 1
  strategy:
  selector:
    matchLabels:
      app: yata-db
  template:
    metadata:
      labels:
        app: yata-db
    spec:
      volumes:
        - name: yata-db-storage-volume
          persistentVolumeClaim:
            claimName: yata-db-pvc
      containers:
      - name: postgres
        image: postgres:12
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: yata-db-storage-volume
        env:
          - name: POSTGRES_DB
            value: yata
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: pguser
                key: value
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pguser
                key: value
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
