APP_ENV      = ENV['APP_ENV'] || 'development'
APP_PROTOCOL = ENV['APP_PROTOCOL']
APP_HOST     = ENV['APP_HOST']
APP_PORT     = ENV['APP_PORT']

FULL_HOST = "#{APP_PROTOCOL}://#{APP_HOST}:#{APP_PORT}"
