apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yata-db-pvc
  labels:
    vol: yata-db-storage
spec:
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
